# Site settings
name: Gnyana Teja Samudrala
title: Gnyana Teja Samudrala | Robotics Engineer
description:  I'm an enthusiast in the field of machine learning and artificial intelligence.
url: https://sgteja.me/
baseurl: ""
email: gnyanateja@gmail.com
cover: https://sgteja.me/img/bg-intro/GOPR0514.jpg
logo: https://sgteja.me/img/logo-white.png
resume: https://sgteja.me/resume.pdf
social:
  - title: email
    url: mailto:gnyanateja@gmail.com
#  - title: twitter
#   url: https://twitter.com/
  - title: instagram
    url: https://instagram.com/gnyanateja
#  - title: codepen
#    url: https://codepen.io/
  - title: github
    url: https://github.com/sgteja
  - title: linkedin
    url: https://www.linkedin.com/in/gnyana-teja
# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
