- row: row1
  services:
    - heading: Statistical Pattern Recognition
      sprite: webdev
      text: Through this course, I’ve have learned the recognition and analysis of mathematical patterns. This course emphasis on parametric and non-parametric statistical pattern recognition methods and clustering. My academic projects for this course work focused on applications of image recognition.

    - heading: Deep Learning Approaches for Computer Vision
      sprite: ui
      text: Through this course, I learned image formation, features, segmentation, stitching, recognition, motion estimation, and 3D point clouds. The coursework showcased how to model classical 3D geometrical problems using Deep Learning. Various projects were carried out throughout the course based on both conventional and deep learning approaches.

- row: row2
  services:
    - heading: Robot Modelling 
      sprite: xd
      text: Robot Modelling focused on the modeling of manipulators based on serial mechanisms. I studied the concepts related to kinematics, inverse kinematics, and Jacobians. I also learned Eulerian and Lagrangian Dynamics. I was elated to use simulation software such as ROS and VREP for academic projects.

    - heading: Rehabilitation Robotics
      sprite: wit
      text: Rehabilitation Robotics provided an introduction to a field of robotics, that is dedicated to improving the lives of people with disabilities. The course considers not only engineering design and development but also human factors that make some innovative technologies successful and improvise in improving other commercial failures. The coursework discusses sensing, actuation, and control principles used across multiple rehabilitation robots.
